### ISSUE TITLE
Can't create global issue with files

### ISSUE THREAD

**Issue by rafaelmartinsrm** [acosonic/redmine_multiproject_issue_adder#3]
When I try to create an issue with an attachment, only the first issue is created. The other ones return that it could not be saved.

**Comment by acosonic** [comment]
Hi, ok... Will have to investigate that...

**Comment by acosonic** [comment]
It should be fixed now by @bilel-kedidi  in revision bilel-kedidi@ee093a095e2a7cb2d7552d31eaa0b9d222482576
